"""crear enum estado_propiedad y tabla propiedades

Revision ID: d7d37c034e18
Revises: 001_bootstrap
Create Date: 2026-06-14 16:24:50.240413

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7d37c034e18"
down_revision: str | Sequence[str] | None = "001_bootstrap"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "propiedades",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("direccion", sa.String(length=255), nullable=False),
        sa.Column("ciudad", sa.String(length=100), nullable=False),
        sa.Column("precio_mensual", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("habitaciones", sa.Integer(), nullable=False),
        sa.Column("banos", sa.Integer(), nullable=False),
        sa.Column("area", sa.Integer(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "disponible",
                "rentada",
                "mantenimiento",
                "inactiva",
                name="estado_propiedad",
            ),
            nullable=False,
        ),
        sa.Column("imagen", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "titulo", "direccion", "ciudad", name="uq_propiedades_identidad_negocio"
        ),
        comment="Propiedades inmobiliarias del sistema Realtor",
    )
    op.create_index("ix_propiedades_ciudad", "propiedades", ["ciudad"], unique=False)
    op.create_index("ix_propiedades_estado", "propiedades", ["estado"], unique=False)
    op.create_index(
        "ix_propiedades_precio_mensual", "propiedades", ["precio_mensual"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_propiedades_precio_mensual", table_name="propiedades")
    op.drop_index("ix_propiedades_estado", table_name="propiedades")
    op.drop_index("ix_propiedades_ciudad", table_name="propiedades")
    op.drop_table("propiedades")
    op.execute("DROP TYPE IF EXISTS estado_propiedad")
    # ### end Alembic commands ###
